### ISSUE TITLE
Add default style to icons to automatically adapt their size and position to the surrounding text

### ISSUE THREAD

**Issue by cseguenot** [11ty/eleventy-plugin-font-awesome#5]
Hello !

Thank you for this very useful plugin!
To further simplify the integration of icons, since Font Awesome's standard size attributes (ex. `fa-sm` or `fa-x2`) are not supported, the following default style should be assigned to all icons:

```css
.size-1 {
  vertical-align: baseline;
  margin: 0 0.3em;
  width: 1em;
  height: 1em;
}
```

This way, the icons would automatically adapt their size and position to the surrounding text, whether they are placed in a `<p>` or `<h>` element for example.
